name: Node.js CI - job

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Install dependencies
      working-directory: ./server
      run: npm install
    
    - name: Run test
      working-directory: ./server
      run: npm test
    
    - name: Build
      working-directory: ./server
      run: npm run build
