name: Python CI - job

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python_workstream

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
